apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platformma-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/EXAMPLE_REPO.git
    targetRevision: main
    path: helm/platformma-app
    helm:
      releaseName: platformma
  destination:
    server: https://kubernetes.default.svc
    namespace: platformma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
